site_title = "MyArxiv"
limit_days = 14
cache_url = "https://Yiyi-philosophy.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"


[[sources]]
limit = 150
category = "cs.PF"
title = "Performance"

[[sources]]
limit = 50
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 50
category = "cs.OS"
title = "Operating Systems"

[[sources]]
limit = 50
category = "cs.DB"
title = "Databases"

[[sources]]
limit = 50
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 10
category = "cs.GT"
title = "Computer Science and Game Theory"

[[sources]]
limit = 10
category = "cs.IT"
title = "Information Theory"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
